### PR TITLE
💄🎨1074 cmd ui add communication preference to notification preferences page

### PR DESCRIPTION
**Pull request by jonhindle**

### CODE REVIEW

**Comment by astroash** [comment]
Are we going to continue storing email and mobile numbers in two separate places? From a UX POV it seems weird that I need to add my email and number on the notification preferences page, and that separate details to these are stored on my account settings page

**Comment by jonhindle** [comment]
So there are two reasons behind this. One is to do with access restrictions between apps. The other is that you may want notifications sent to another none work device whether it be email or sms; the account service doesn't cater for this because as yet, its not a generic requirement.

**Comment by astroash** [comment]
> One is to do with access restrictions between apps.

It's not clear from a UX perspective that users are using two different apps. It looks like their on the same page and in one place their email address is `X` and in the other place their email address isn't set

>The other is that you may want notifications sent to another none work device whether it be email or sms

This isn't explained in copy anywhere on the app. Also, a potential security issue that these additional contact details are not confirmed/double typed to ensure they are going to the correct place.

FYI, none of these comments are blocking, just raising issues/thoughts I come across whilst trying to use the app myself.

**Comment by jonhindle** [comment]
None of these points are introduced by this change though. I think there is value in raising a ticket to rethink the UX here though 👍 
1093-notifications-settings-ux-rethink

**Comment by nickmcmahon01** [comment]
yeah, the Auth service doesn't support storing extra stuff about other services functionality (and shouldn't IMO)
it also restricts access to that private data.

**Pull request merged**
